os:
  - linux

language: php

php:
  - '7.1'

addons:
  mariadb: '10.3'
  
env:
  - CODACY_PROJECT_TOKEN=77720ad6423143de8bcba89bc6bb8e02

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - npm install npm@latest -g
  - npm install
  - php artisan telescope:install
  - npm install --save laravel-vue-pagination
  - npm install --save feather-icons vue-feather
  - php artisan key:generate
  - php artisan migrate --step
  - php artisan db:seed
  
script:
  - php vendor/bin/codacycoverage phpunit
  - npm run production

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml
