os:
  - linux

language: php

php:
  - '7.1'

addons:
  mariadb: '10.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - npm install npm@latest -g
  - npm install
  - php artisan key:generate
  - php artisan migrate --step
script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
