os:
  - linux

language: php

php:
  - '7.1'

addons:
  mariadb: '10.3'
  
env:
  global:
    CC_TEST_REPORTER_ID=9b5f9ebc336d9e4b149bb4a3a7bdc594c508b5c193d1b65f2480f02a755ecd72

before_script: 
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 
- chmod +x ./cc-test-reporter 
- ./cc-test-reporter before-build

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - npm install npm@latest -g
  - npm install
  - php artisan telescope:install
  - npm install --save laravel-vue-pagination
  - npm install --save feather-icons vue-feather
  - php artisan key:generate
  - php artisan migrate --step
  - php artisan db:seed
  
script:
  - vendor/bin/codecept run unit --coverage --coverage-xml
  - npm run production

after_script: 
- mv tests/_output/coverage.xml clover.xml 
- ./cc-test-reporter after-build --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT
